// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/assessments" | "/awaiting-specialty" | "/changePassword" | "/config" | "/config/dde" | "/config/printers" | "/config/printers/[id]/edit" | "/config/printers/create" | "/config/users/[id]" | "/config/users/create" | "/dashboard" | "/dispositions" | "/initial-registration" | "/initial-registration/list" | "/investigations" | "/login" | "/medications" | "/patient" | "/patient/[id]/consultation" | "/patient/[id]/continuationSheet" | "/patient/[id]/differential-diagnosis" | "/patient/[id]/disposition" | "/patient/[id]/final-diagnosis" | "/patient/[id]/gyneacology" | "/patient/[id]/investigations" | "/patient/[id]/medicalHistory" | "/patient/[id]/medicalInpatient" | "/patient/[id]/medicalInpatient-" | "/patient/[id]/nursingChart" | "/patient/[id]/orthopaedic-specialty-review" | "/patient/[id]/patient-management-plan" | "/patient/[id]/primary-assessment" | "/patient/[id]/profile" | "/patient/[id]/secondary-assessment" | "/patient/[id]/soap" | "/patient/[id]/surgicalNotes" | "/patient/[id]/trauma-specialty-review" | "/patient/[id]/view" | "/prescreening" | "/prescreening/[id]" | "/radiology" | "/radiology/[type]" | "/registration" | "/registration/[id]/new" | "/registration/[id]/search" | "/registration/death" | "/registration/death/[id]/edit" | "/registration/death/[id]/view" | "/registration/death/list" | "/registration/list" | "/registration/new" | "/registration/scanner" | "/registration/search" | "/registration/search/[id]" | "/reports" | "/test" | "/test-results" | "/triage" | "/triage/[id]/history" | "/triage/[id]/start" | "/vitals"
type AppRouteHandlerRoutes = "/api/log-client-error"
type PageRoutes = never
type LayoutRoutes = "/" | "/config"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/log-client-error": {}
  "/assessments": {}
  "/awaiting-specialty": {}
  "/changePassword": {}
  "/config": {}
  "/config/dde": {}
  "/config/printers": {}
  "/config/printers/[id]/edit": { "id": string; }
  "/config/printers/create": {}
  "/config/users/[id]": { "id": string; }
  "/config/users/create": {}
  "/dashboard": {}
  "/dispositions": {}
  "/initial-registration": {}
  "/initial-registration/list": {}
  "/investigations": {}
  "/login": {}
  "/medications": {}
  "/patient": {}
  "/patient/[id]/consultation": { "id": string; }
  "/patient/[id]/continuationSheet": { "id": string; }
  "/patient/[id]/differential-diagnosis": { "id": string; }
  "/patient/[id]/disposition": { "id": string; }
  "/patient/[id]/final-diagnosis": { "id": string; }
  "/patient/[id]/gyneacology": { "id": string; }
  "/patient/[id]/investigations": { "id": string; }
  "/patient/[id]/medicalHistory": { "id": string; }
  "/patient/[id]/medicalInpatient": { "id": string; }
  "/patient/[id]/medicalInpatient-": { "id": string; }
  "/patient/[id]/nursingChart": { "id": string; }
  "/patient/[id]/orthopaedic-specialty-review": { "id": string; }
  "/patient/[id]/patient-management-plan": { "id": string; }
  "/patient/[id]/primary-assessment": { "id": string; }
  "/patient/[id]/profile": { "id": string; }
  "/patient/[id]/secondary-assessment": { "id": string; }
  "/patient/[id]/soap": { "id": string; }
  "/patient/[id]/surgicalNotes": { "id": string; }
  "/patient/[id]/trauma-specialty-review": { "id": string; }
  "/patient/[id]/view": { "id": string; }
  "/prescreening": {}
  "/prescreening/[id]": { "id": string; }
  "/radiology": {}
  "/radiology/[type]": { "type": string; }
  "/registration": {}
  "/registration/[id]/new": { "id": string; }
  "/registration/[id]/search": { "id": string; }
  "/registration/death": {}
  "/registration/death/[id]/edit": { "id": string; }
  "/registration/death/[id]/view": { "id": string; }
  "/registration/death/list": {}
  "/registration/list": {}
  "/registration/new": {}
  "/registration/scanner": {}
  "/registration/search": {}
  "/registration/search/[id]": { "id": string; }
  "/reports": {}
  "/test": {}
  "/test-results": {}
  "/triage": {}
  "/triage/[id]/history": { "id": string; }
  "/triage/[id]/start": { "id": string; }
  "/vitals": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/config": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
