// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments">> = Specific
  const handler = {} as typeof import("../../app/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/awaiting-specialty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/awaiting-specialty">> = Specific
  const handler = {} as typeof import("../../app/awaiting-specialty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/changePassword/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changePassword">> = Specific
  const handler = {} as typeof import("../../app/changePassword/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/config/dde/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config/dde">> = Specific
  const handler = {} as typeof import("../../app/config/dde/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config">> = Specific
  const handler = {} as typeof import("../../app/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/config/printers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config/printers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/config/printers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/config/printers/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config/printers/create">> = Specific
  const handler = {} as typeof import("../../app/config/printers/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/config/printers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config/printers">> = Specific
  const handler = {} as typeof import("../../app/config/printers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/config/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/config/users/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/config/users/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/config/users/create">> = Specific
  const handler = {} as typeof import("../../app/config/users/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dispositions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispositions">> = Specific
  const handler = {} as typeof import("../../app/dispositions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/initial-registration/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/initial-registration/list">> = Specific
  const handler = {} as typeof import("../../app/initial-registration/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/initial-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/initial-registration">> = Specific
  const handler = {} as typeof import("../../app/initial-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investigations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investigations">> = Specific
  const handler = {} as typeof import("../../app/investigations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/medications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/medications">> = Specific
  const handler = {} as typeof import("../../app/medications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/consultation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/consultation">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/consultation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/continuationSheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/continuationSheet">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/continuationSheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/differential-diagnosis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/differential-diagnosis">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/differential-diagnosis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/disposition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/disposition">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/disposition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/final-diagnosis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/final-diagnosis">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/final-diagnosis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/gyneacology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/gyneacology">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/gyneacology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/investigations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/investigations">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/investigations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/medicalHistory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/medicalHistory">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/medicalHistory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/medicalInpatient-/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/medicalInpatient-">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/medicalInpatient-/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/medicalInpatient/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/medicalInpatient">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/medicalInpatient/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/nursingChart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/nursingChart">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/nursingChart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/orthopaedic-specialty-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/orthopaedic-specialty-review">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/orthopaedic-specialty-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/patient-management-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/patient-management-plan">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/patient-management-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/primary-assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/primary-assessment">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/primary-assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/profile">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/secondary-assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/secondary-assessment">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/secondary-assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/soap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/soap">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/soap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/surgicalNotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/surgicalNotes">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/surgicalNotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/trauma-specialty-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/trauma-specialty-review">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/trauma-specialty-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/[id]/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/[id]/view">> = Specific
  const handler = {} as typeof import("../../app/patient/[id]/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient">> = Specific
  const handler = {} as typeof import("../../app/patient/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/prescreening/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prescreening/[id]">> = Specific
  const handler = {} as typeof import("../../app/prescreening/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/prescreening/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prescreening">> = Specific
  const handler = {} as typeof import("../../app/prescreening/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/radiology/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/radiology/[type]">> = Specific
  const handler = {} as typeof import("../../app/radiology/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/radiology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/radiology">> = Specific
  const handler = {} as typeof import("../../app/radiology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/[id]/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/[id]/new">> = Specific
  const handler = {} as typeof import("../../app/registration/[id]/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/[id]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/[id]/search">> = Specific
  const handler = {} as typeof import("../../app/registration/[id]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/death/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/death/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/registration/death/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/death/[id]/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/death/[id]/view">> = Specific
  const handler = {} as typeof import("../../app/registration/death/[id]/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/death/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/death/list">> = Specific
  const handler = {} as typeof import("../../app/registration/death/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/death/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/death">> = Specific
  const handler = {} as typeof import("../../app/registration/death/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/list">> = Specific
  const handler = {} as typeof import("../../app/registration/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/new">> = Specific
  const handler = {} as typeof import("../../app/registration/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration">> = Specific
  const handler = {} as typeof import("../../app/registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/scanner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/scanner">> = Specific
  const handler = {} as typeof import("../../app/registration/scanner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/search/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/search/[id]">> = Specific
  const handler = {} as typeof import("../../app/registration/search/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registration/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/search">> = Specific
  const handler = {} as typeof import("../../app/registration/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-results">> = Specific
  const handler = {} as typeof import("../../app/test-results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test">> = Specific
  const handler = {} as typeof import("../../app/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/triage/[id]/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/triage/[id]/history">> = Specific
  const handler = {} as typeof import("../../app/triage/[id]/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/triage/[id]/start/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/triage/[id]/start">> = Specific
  const handler = {} as typeof import("../../app/triage/[id]/start/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/triage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/triage">> = Specific
  const handler = {} as typeof import("../../app/triage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vitals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vitals">> = Specific
  const handler = {} as typeof import("../../app/vitals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/log-client-error/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/log-client-error">> = Specific
  const handler = {} as typeof import("../../app/api/log-client-error/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/config/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/config">> = Specific
  const handler = {} as typeof import("../../app/config/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
